site_name: "numfolio"

theme:
  name: readthedocs
  theme:
    palette:
      scheme: slate
      primary: teal

use_directory_urls: false
nav:
  - Home: 'index.md'
  - API:
      - Index: 'api/index.md'
      - Stats: 'api/stats/stats.md'
      - Core: 'api/core/core.md'
  - About:
      - 'License': 'license.md'
      - 'Authors': 'authors.md'

plugins:
  - search
  - mkdocstrings:
     handlers:
       python:
         paths: [../numfolio]
       options:
         inherited_members: true
         show_source : false
